config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :players, only: [:new, :index, :create, :show, :destroy]

  resources :games do
    resources :scores, only: [:new, :create, :index]
  end

  root to: "pages#dashboard"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :player_one, class_name: "Player"
  belongs_to :player_two, class_name: "Player"
  has_many :scores
  has_many :players, through: :scores
end

app/models/player.rb
class Player < ApplicationRecord
  has_many :scores
  has_many :games, through: :scores
end

app/models/player_game.rb
class PlayerGame < ApplicationRecord
  belongs_to :player
  belongs_to :game
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :player
  belongs_to :score
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :update, :edit, :destroy]
  before_action :set_player, only: [:create]

  def index
    @games = Game.all
    @score = Score.new
    @player_one = Player.find_by_id(params[:player_one_id])
    @player_two = Player.find_by_id(params[:player_two_id])

  end

  def create
    @game = Game.new(game_params)
    @player = Player.new
    if @game.save
      redirect_to games_path
    else
      render 'pages/dashboard'
    end
  end

  def new
    @game = Game.new
  end

  def show
  end

  def edit
    @game = Game.find(params[:id])
    @player_one = @game.player_one
    @player_two = @game.player_two
    # if @game.win == @player_one
    #   @game.lost == @player_two
    # else
    #   @game.lost == @player_one
    # end
  end

  def update
    if @game.update(game_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  def destroy
    @game.destroy
    redirect_to root_path
  end

  private

  def set_game
    @game = Game.find(params[:id])
  end

  def set_player
    @player = Player.find_by_id(params[:player])
  end

  def game_params
    params.require(:game).permit(:results, :player_one_id, :player_two_id, :win, :lost)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def dashboard
    @player = Player.new
    @players = Player.all
    @game = Game.new
    @games = Game.all
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :destroy]

  def index
    @players = Player.all
    @score = Score.new

  end

  def create
    @player = Player.new(player_params)
    if @player.save
      redirect_to players_path
    else
      render 'pages/dashboard'
    end
  end

  def new
    @player = Player.new
  end

  def show
    @scores = Score.where(player_id: @player)
  end

  def destroy
    @player.destroy
    redirect_to players_path
  end

  private

  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name)
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  before_action :set_player
  before_action :set_game

  def index
    @scores = Score.all
  end

  def new
    @score = Score.new
  end

  def create
    @score.player_id = @winner
    @score = Score.new(score_params)
    if @score.save
      redirect_to game_path(@game)
    else
      render 'pages/dashboard'
    end
  end

  private

  def set_game
    @game = Game.find(params[:game_id])
  end

  def set_player
    @game = Game.find(params[:game_id])
    if @game.win.to_i === @game.player_one_id
      @winner = Player.find(@game.player_one_id)
    elsif @game.win.to_i === @game.player_two_id
      @winner = Player.find(@game.player_two_id)
    end
  end

  def score_params
    params.permit(:game_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/views/games/_form.html.erb
<%= simple_form_for [@game] do |f| %>
  <%= f.input :win, collection: [@player_one, @player_two] %>
  <%= f.input :lost, collection: [@player_one, @player_two] %>
  <%= f.submit 'Save', class: 'btn btn-primary' %>
<% end %>

app/views/games/edit.html.erb
<div class="container">
  <%= render 'form' %>

  <%= link_to 'BACK', root_path %>
</div>

app/views/games/index.html.erb
<h1>This is a list of all games</h1>

<div class="container">
  <ul>
    <% @games.order(:created_at).reverse.each do |game| %>
      <li>
        <%= game.player_one.name %> - <%= game.player_two.name %> |
        <%= (game.win.to_i === game.player_one_id) ? '1 - 0' : '0 - 1' %>
        <br>
        <%= game.created_at.strftime("%d/%m/%Y %H:%M") %>
        <br>
        <%= link_to "UPDATE RESULT", edit_game_path(game), class: 'btn btn-info' %>
        <%= link_to "DELETE", game_path(game), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-info' %>
      </li>
    <% end %>
  </ul>

<%= link_to "BACK", root_path, class: 'btn btn-info' %>
</div>

app/views/games/new.html.erb
<div class="container">
  <%= simple_form_for(@game) do |g| %>

    <div class="form-inputs">
      <%= g.input :name, collection: [@players] %>
    </div>

    <div class="form-inputs">
      <%= g.input :name, collection: [@players] %>
    </div>

    <div class="form-actions">
      <%= g.button :submit, 'CREATE', class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rentoo League</title>

    <%= csrf_meta_tags %>
    <link rel="icon" type="image/jpg" href="<%= image_url('favicon.png') %>" >
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat:400,700|Oswald:300,400,700">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <div class='navbar'>
      <%= render 'shared/navbar' %>
    </div>
    <%= yield %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">
  <h1>Rentoo Ping Pong League</h1>

  <div class='top-league'>
    <table>
      <thead>
        <tr>
          <td>#</td>
          <td>Name</td>
          <td>Won</td>
          <td>Lost</td>
          <td>Winning %</td>
          <td>Points</td>
        </tr>
      </thead>

      <tbody>
        <% @players.each do |player| %>
          <tr>
            <td><%= player.id %></td>
            <td><%= player.name %></td>
            <td></td>
            <td></td>
            <td>%</td>
            <td></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

  <div class="row">
    <div class="col-xs-6 col-sm-4">
      <div class='player-new'>
        <%= simple_form_for(@player) do |p| %>
          <% if @player.errors.any? %>
            <div class="errors-container">
              <ul>
                <% @player.errors.full_messages.each do |message| %>
                  <li><%= message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="form-inputs">
            <%= p.input :name, label: 'Add a new player', placeholder: "e.g. Bob", :label_html => { class: 'type' } %>
          </div>

          <div class="form-actions">
            <%= p.button :submit, 'Add player', class: "btn btn-info" %>
          </div>
        <% end %>
      </div>
    </div>

    <div class="col-xs-6 col-sm-4">
      <div class="add-game">
        <h3 class='new-game'>Add Games</h3>
        <div class=game-players>
          <%= simple_form_for(@game) do |g| %>
            <% if @game.errors.any? %>
              <div class="errors-container">
                <ul>
                  <% @game.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>
            <div class="form-inputs">
              <%= g.input :player_one_id, collection: Player.all, :label_html => { class: 'type' } %>
            </div>
            <div class="form-inputs">
              <%= g.input :player_two_id, collection: Player.all, :label_html => { class: 'type' } %>
            </div>
            <div class="form-actions">
              <%= g.button :submit, 'Add game', class: "btn btn-info" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="col-xs-6 col-sm-4">
      <div class='game-result'>
        <h3 class='latest-game'>Latest Games</h3>
        <div class='game-list'>
          <% @games.order(:created_at).reverse[0..2].each do |game| %>
            <p>
              <%= game.player_one.name %>
              <%= (game.win.to_i === game.player_one_id) ? '1' : '0' %>
              -
              <%= (game.win.to_i === game.player_one_id) ? '0' : '1' %>
              <%= game.player_two.name %>
            </p>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/players/index.html.erb
<div class="container">
  <table>
    <thead>
      <tr>
        <td></td>
        <td>Name</td>
        <td>Games</td>
        <td>Scores</td>
        <td></td>
      </tr>
    </thead>
    <tbody>
      <% @players.each do |player| %>
        <tr>
          <td><%= player.id %></td>
          <td><%= player.name %></td>
          <td>games for this player</td>
          <td>scores</td>
          <td><%= link_to "Delete", player_path(player), method: :delete, data: { confirm: 'Are you certain you want to delete this?' }, class: 'btn btn-info' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<br>

<%= link_to "BACK", root_path, class: 'btn btn-info' %>
</div>

app/views/players/new.html.erb
<div class="container">
  <%= simple_form_for(@player) do |p| %>
    <% if @player.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @player.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-inputs">
      <%= p.input :name, placeholder: "Enter your name" %>
    </div>

    <div class="form-actions">
      <%= p.button :submit, 'CREATE', class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/players/show.html.erb
<h1>this is a show page for single player</h1>

<%= @scores.count %>

app/views/scores/_form.html.erb
<%= simple_form_for [game, @score] do |f| %>
  <% if @score.errors.any? %>
    <div class="errors-container">
      <ul>
        <% @score.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.input :player_id, collection: [game.win] %>
  <%= f.submit 'NEW SCORE', class: 'btn btn-primary' %>
<% end %>

app/views/scores/new.html.erb
<div class="container">
  <%= simple_form_for([@player, @score]) do |s| %>
    <% if @score.errors.any? %>
      <div class="errors-container">
        <ul>
          <% @score.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-actions">
      <%= s.button :submit, 'NEW', class: "btn btn-info" %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <!-- Logo -->
  <div class="navbar-left">

    <div class="navbar-logo">
      <%= link_to root_path do %>
        <%= image_tag "favicon.png" %>
      <% end %>
    </div>

    <div class="navbar-brand">
      <p>Rentoo</p>
    </div>
  </div>
  <div class="navbar-right">
    <div class="navbar-games">
      <%= link_to "ALL GAMES", games_path, class: 'navbar-link' %>
    </div>| &nbsp &nbsp
    <div class="navbar-players">
      <%= link_to "ALL PLAYERS", players_path, class: 'navbar-link' %>
    </div>
  </div>
</div>